# Site settings
title: "Clémence Réda"
username: "Clémence Réda"
user_title: "Marie Skłodowska-Curie Postdoctoral Fellow at Universität Rostock since 2023/05"
description: #>- this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.clreda.github.io

host: 0.0.0.0
port: 4080
google_analytics: G-KKE9ZM79MV #UA-123473849-1

plugins: ["jekyll-seo-tag"]

publications:
projects:

email: clemence.reda@uni-rostock.de
github_username:  clreda
discord_username:  kureda
linkedin_username: clemence-reda
gscholar_username: q3AUHgEAAAAJ
orcid_username: 0000-0003-3238-0258
address: "Systembiologie und Bioinformatik Rostock, Ulmenstraße 69, 18059 Rostock, Germany"

encoding: UTF-8

exclude: ['package.json', 'src' , 'node_modules']
