title: "Homepage of Clémence Réda"
description: #>- this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.clreda.github.io

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

host: 0.0.0.0
port: 4080
google_analytics: G-KKE9ZM79MV #UA-123473849-1

plugins: ["jekyll-seo-tag"]

publications: 
projects:

email: clemence.reda@inserm.fr
github_username:  clreda
discord_username:  kureda
address: "Bât Bingen, 48 boulevard Sérurier, 75019 Paris, France"

encoding: UTF-8

exclude: ['package.json', 'src' , 'node_modules']
