# Site settings
title: "Clémence Réda"
username: "Clémence Réda"
user_title: "Research at IBENS since 2025/02"
description: #>- this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: https://clreda.github.io

host: 0.0.0.0
port: 4080
google_analytics: G-KKE9ZM79MV #UA-123473849-1

plugins: ["jekyll-seo-tag"]

publications:
projects:

email: reda@biologie.ens.fr
github_username:  clreda
discord_username:  kureda
linkedin_username: clemence-reda
gscholar_username: q3AUHgEAAAAJ
orcid_username: 0000-0003-3238-0258
researchgate_username: Clemence-Reda
address: "46, rue d'Ulm, 75005 Paris, France"

encoding: UTF-8

exclude: ['package.json', 'src' , 'node_modules']
